graph LR
    FaceRegistration(Face Registration)--> FaceRecognition(Face Recognition) 
    FaceRegistration-->DataStorage
    FaceRecognition(Face Recognition) -->DataStorage
    DataStorage[(Database)]-->ER(ER Diagram)
    Website
    ModifyDjangoUser
    WebCameraLibrary(OpenCV.js)--images-->Website(Django)-->FaceRegistration.py
    
    
