gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Implementation
      Perpare demo deploy/laptop :a2, after a1  , 3d
      Fill Database with dummy data: after a1  , 3d
      Demo-users :after a1  , 3d
      Cleanup Model    :a1, 2023-02-09, 3d
      Secure Paths    :after a1  , 2d
      Tidy up the sign-in     :after a1  , 3d
      Day Roaster     :a3, after a2  , 1d
      Style Editors     :after a1  , 2d
      Congi Admin Section     :after a1  , 2d
    section Testing
      Unit Test      :2023-02-09  , 5d
    section Presentation
      Document delerivery :2023-02-09  , 5d
      Presentation      : 3d