gantt
    title What's Left
    dateFormat  YYYY-MM-DD
    section Implementation
      Perpare demo deploy/laptop :done, a2, after a1  , 3d
      Fill Database with dummy data: after a1  , 3d
      Demo-users :after a1  , 3d
      Cleanup Model    :done, a1, 2023-02-09, 3d
      Secure Paths    :done,crit,,after a1  , 2d
      Tidy up the sign-in     :done, after a1  , 3d
      Day Roster     :done,a3, after a2  , 1d
      Tidy up Edit Profile (Style) :after a1  , 2d
      Config Admin Section     :done, after a1  , 2d
    section Testing
      Unit Test      :done,2023-02-09  , 5d
    section Presentation
      Document delerivery :2023-02-09  , 5d
      Presentation      : 3d