# Generated by Django 3.2.5 on 2023-01-19 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_in_date', models.DateTimeField(auto_now_add=True, verbose_name='date signed in')),
                ('sign_out_date', models.DateTimeField(auto_now_add=True, verbose_name='date signed out')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.location')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.location')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
