# Generated by Django 3.2.5 on 2023-02-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpermission',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='locationpermission',
            old_name='user_account_id',
            new_name='user_account',
        ),
        migrations.RenameField(
            model_name='roster',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='roster',
            old_name='user_account_id',
            new_name='user_account',
        ),
    ]
